In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
ts_train = pd.read_csv('train.csv')
ts_test = pd.read_csv('test.csv')
tsdata = pd.concat([ts_train, ts_test])
tsdata = tsdata.reset_index(drop=True)
display(tsdata)
tsdata.isnull().sum()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [4]:
tsdata = tsdata.drop(["PassengerId", "Pclass", "Name",
                     'Age', 'Parch', 'Ticket', 'Fare',
                     'Cabin','Embarked'], axis=1)
tsdata

      Survived     Sex  SibSp
0          0.0    male      1
1          1.0  female      1
2          1.0  female      0
3          1.0  female      1
4          0.0    male      0
...        ...     ...    ...
1304       NaN    male      0
1305       NaN  female      0
1306       NaN    male      0
1307       NaN    male      0
1308       NaN    male      1

[1309 rows x 3 columns]

In [15]:
cl_tsdata = tsdata['Survived'].isnull()==False 
trn_tsdata = tsdata[cl_tsdata]
trn_tsdata['Survived'] = trn_tsdata['Survived'].astype(int)

trn_tsdata

     Survived     Sex  SibSp
0           0    male      1
1           1  female      1
2           1  female      0
3           1  female      1
4           0    male      0
..        ...     ...    ...
886         0    male      0
887         1  female      0
888         0  female      1
889         1    male      0
890         0    male      0

[891 rows x 3 columns]

In [10]:
trn_tsdata['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [26]:
X = trn_tsdata.drop(columns = ['Sex','SibSp'], axis=1)
X.head()

   Survived
0         0
1         1
2         1
3         1
4         0

In [27]:
y = trn_tsdata['Survived']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int32

In [28]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_std = std.fit_transform(X)
X_std

array([[-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [ 1.2669898 ],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234],
       [ 1.2669898 ],
       [-0.78927234]])

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.20, random_state=0)

In [30]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train, y_train)
logr.score(X_test, y_test)

1.0